// src/lib/circulars.js
// Real circulars data.

export const circularsByYear = {
  "2025": [
    { id: 25117, headline: "Circular for selection of players", href: "#" },
    { id: 25116, headline: "Internal Circular for Application Engineer(customer Services) of CMO", href: "#" },
    { id: 25115, headline: "Circular for Jawahar DICs Excellence and Jawaharlal Nehru Group Award 2025", href: "#" },
    { id: 25114, headline: "CIRCULAR-Implementation Of Online Final Settlement Module for Superannuting Employees.", href: "#" },
    { id: 25113, headline: "CIRCULAR-Nehru Award 2025", href: "#" },
    { id: 25112, headline: "Circular for SAIL Corporate Awards for Excellence 2025 Scheme", href: "#" },
    { id: 25111, headline: "Circular for selection to the post of Dir(Commercial), SAIL.through SCSC method", href: "#" },
    { id: 25110, headline: "Internal Circular for filling up various critical positions in ISP", href: "#" },
    { id: 25109, headline: "CIRCULAR-Health Check-up of Non Executive Employees For Oct 2025", href: "#" },
    { id: 25108, headline: "Circular-Online complaint management system titled Sexual Harassment electronic Box (SHe-Box)", href: "#" },
    { id: 25107, headline: "Circular for selection for the post of Director (Finance), NMDC Ltd", href: "#" },
    { id: 25106, headline: "Circular for iGOT-Karmayogi", href: "#" },
    { id: 25105, headline: "Circular-TT Circular Selection of Players", href: "#" },
    { id: 25104, headline: "CIRCULAR-VISHWAKARMA PUJA 2025", href: "#" },
    { id: 25103, headline: "CIRCULAR-PAKHWADA", href: "#" },
    { id: 25102, headline: "CIRCULAR-Employee Assistance Programme (EAP) Counselling Sessions at DSP", href: "#" },
    { id: 25101, headline: "CIRCULAR- NATIONAL SPORTS DAY 2025", href: "#" },
    { id: 25100, headline: "CIRCULAR-Health Check up of Non-Executive Employees for SEPTEMBER-2025", href: "#" },
    { id: 25099, headline: "CIRCULAR-PUBLIC UTILITY SERVICE", href: "#" },
    { id: 25098, headline: "CIRCULAR- INTER DEPARTMENT TABLE TENNIS TOURNAMENT-2025", href: "#" },
    { id: 25097, headline: "CIRCULAR- SAIL MEDICLAIM RENEWAL (EXTN)", href: "#" },
    { id: 25096, headline: "CIRCULAR-Online Application For Reimbursement of Mobile Handset For Executives", href: "#" },
    { id: 25095, headline: "Manpower requirement in JPC", href: "#" },
    { id: 25094, headline: "Circular for selection of various posts for ICVL Mozambique Operation", href: "#" },
    { id: 25093, headline: "CIRCULAR- SAIL MEDICLAIM RENEWAL (EXTN)", href: "#" },
    { id: 25092, headline: "Circular - Hindi Teaching Scheme - July-Nov25 Session", href: "#" },
    { id: 25091, headline: "CIRCULAR -OUTSTATION MEDICAL FACILITY FOR DEPENDENT CHILDREN", href: "#" },
    { id: 25090, headline: "CIRCULAR-Health Check-up of non-executive employees for AUGUST 2025", href: "#" },
    { id: 25089, headline: "CIRCULAR- BAMS-HANDHELD DEVICE AT GATE", href: "#" },
    { id: 25088, headline: "Circular Netaji Subhas Chandra Bose Excellence Award 2025", href: "#" },
    { id: 25087, headline: "CIRCULAR APPROVED WAGE RATES WEF 01.07.2025", href: "#" },
    { id: 25086, headline: "CIRCULAR-FESTIVAL ADVANCE", href: "#" },
    { id: 25085, headline: "Selection for the post of Director (Finance), (RINL) through SCSC Method", href: "#" },
    { id: 25084, headline: "CIRCULAR-DA REVISION", href: "#" },
    { id: 25083, headline: "CIRCULAR-RENEWAL OF SAIL MEDICLAIM 2025-26", href: "#" },
    { id: 25082, headline: "Circular for players selection-Swimming", href: "#" },
    { id: 25081, headline: "Circular for Coach selection-Swimming", href: "#" },
    { id: 25080, headline: "CIRCULAR -TT COURT", href: "#" },
    { id: 25079, headline: "APPEAL", href: "#" },
    { id: 25078, headline: "CIRCULAR-INSULIN SUPPLY&SPECIALINJECTIONS-2025", href: "#" },
    { id: 25077, headline: "CIRCULAR- MEDICINE 30 DAYS CIRCULAR 2025", href: "#" },
    { id: 25076, headline: "Promotion Order E6-E7 dt 30-06-2025", href: "#" },
    { id: 25075, headline: "Promotion Order E5-E6 dt 30-06-2025", href: "#" },
    { id: 25074, headline: "Promotion Order E1-E2, E2-E3, E3-E4 & E4-E5 dt. 30-06-2025", href: "#" },
    { id: 25073, headline: "CIRCULAR-ONE DAY STRIKE ON 09.07.2025", href: "#" },
    { id: 25072, headline: "Circular-Health Check -up of Non - executive employees for JULY 2025", href: "#" },
    { id: 25071, headline: "Circular-Sardar Patel National Unity Award", href: "#" },
    { id: 25070, headline: "INTERNATIONAL YOGA DAY", href: "#" },
    { id: 25069, headline: "Circular- Amendment in the SAIL Resignation Rules.", href: "#" },
    { id: 25068, headline: "Internal Circular Chief Representative Officer", href: "#" },
    { id: 25067, headline: "Circular-Procedure for grant of Special CL for Divyangjan employees", href: "#" },
    { id: 25066, headline: "Circular for selection of Chess Players for DSP Chess Team", href: "#" },
    { id: 25065, headline: "Circular for Coach for DSP Chess Team", href: "#" },
    { id: 25064, headline: "Revised Interview Schedule E3-E4 (WORKS) 2025", href: "#" },
    { id: 25063, headline: "Circular DSP Dance Team- Ispat Nritya Manch", href: "#" },
    { id: 25062, headline: "Revised interview schedule for E5-E6 grade -2025", href: "#" },
    { id: 25061, headline: "Interview schedule for E6-E7 on 04.06.2025", href: "#" },
    { id: 25060, headline: "Interview fro promotionfrom E5-E6 w.e.f. 30.06.2025", href: "#" },
    { id: 25059, headline: "Interview for promotion from E3-E4 w.e.f. 30.06.2025", href: "#" },
    { id: 25058, headline: "Advertisment for the post Executive Secretary in JPC", href: "#" },
    { id: 25057, headline: "CIRCULAR- Health check up of non-executive employees for JUNE-2025", href: "#" },
    { id: 25056, headline: "Circular - Merit Scholarship - 2025", href: "#" },
    { id: 25055, headline: "Circular-Slogan & Drawing Competition for Contractor Workers and their Dependants", href: "#" },
    { id: 25054, headline: "Circular for filling up one post of Executive Secretary, JPC", href: "#" },
    { id: 25053, headline: "CIRCULAR-Reimbursement of Incidental expenses of non-executive trainee", href: "#" },
    { id: 25052, headline: "CIRCULAR-DEFER OF STRIKE NOTICE FOR 20.05.2025", href: "#" },
    { id: 25051, headline: "Circular-Articles invited for Hindi magazine (Spandan)", href: "#" },
    { id: 25050, headline: "Circular - Regularization in BAMS for those candidates who appearing in the May 2025 exam under H T S -Session Jan – May 25.", href: "#" },
    { id: 25049, headline: "CIRCULAR- ONE DAY STRIKE ON 20-05-2025", href: "#" },
    { id: 25048, headline: "CIRCULAR- DA REVISION", href: "#" },
    { id: 25047, headline: "CIRCULAR-Health check up of non-executive employees for MAY-2025", href: "#" },
    { id: 25046, headline: "Interview Schedule for promotion E7-E8", href: "#" },
    { id: 25045, headline: "Scheme for Facilitating Professional Development in Marketing & HRM Function.", href: "#" },
    { id: 25044, headline: "Circular - Closed Holiday on 14.04.2025 - For Contractor Workers", href: "#" },
    { id: 25043, headline: "CIRCULAR-RESCHEDULING OF HEALTH CHECKUP", href: "#" },
    { id: 25042, headline: "CIRCULAR-CLOSED HOLIDAY ON 14.04.2025", href: "#" },
    { id: 25041, headline: "Circular regarding modification in EPMS for E8-E9 grades", href: "#" },
    { id: 25040, headline: "Circular regarding modification in EPMS for E5-E7 grades", href: "#" },
    { id: 25039, headline: "CIRCULAR-Work from Other than Workplace (WoW)", href: "#" },
    { id: 25038, headline: "CIRCULAR-HEALTH CHECK- UP FOR NON-EXECUTIVE EMPLOYEES ( APRIL-2025)", href: "#" },
    { id: 25037, headline: "circular-Cluster-wise redesignation of non-executive employees of DSP", href: "#" },
    { id: 25036, headline: "Internal Circular Chief Representative Officer", href: "#" },
    { id: 25035, headline: "ICVL internal circular", href: "#" },
    { id: 25034, headline: "Notice for Contract Workers-Attendance Capturing through RFID", href: "#" },
    { id: 25033, headline: "Circular-Player Selection for Inter Steel Plants TT Championship", href: "#" },
    { id: 25032, headline: "Circular-Player Selection for Chess Championship", href: "#" },
    { id: 25031, headline: "Circular-Coach Selection for Chess Championship", href: "#" },
    { id: 25030, headline: "CIRCULAR FOR SELECTION OF PLAYERS FOR SPSB VOLLEYBALL TOURNAMENT", href: "#" },
    { id: 25029, headline: "CIRCULAR FOR SELECTION OF COACH FOR SPSB VOLLEYBALL TOURNAMENT", href: "#" },
    { id: 25028, headline: "CIRCULAR FOR SELECTION OF PLAYERS OF DSP TEAM FOR SPSB KABADDI TOURNAMENT", href: "#" },
    { id: 25027, headline: "CIRCULAR FOR SELECTION OF COACH OF DSP TEAM FOR SPSB KABADDI TOURNAMENT", href: "#" },
    { id: 25026, headline: "Circular - Badminton Tournament for Female Employees S", href: "#" },
    { id: 25025, headline: "CIRCULAR FOR INTERNATIONAL WOMENS DAY", href: "#" },
    { id: 25024, headline: "CIRCULAR INTRODUCTION OF EMPLOYEE ASSISTANCE PROGRAMME (EAP)", href: "#" },
    { id: 25023, headline: "CIRCULAR- PUBLIC UTILITY SERVICE", href: "#" },
    { id: 25022, headline: "CIRCULAR-NURSING BREAKS FOR WOMEN EMPLOYEES", href: "#" },
    { id: 25021, headline: "CIRCULAR-HEALTH CHECK-UP SCHEDULED FOR NON-EXECUTIVE EMPLOYEES (MARCH-2025).pdf", href: "#" },
    { id: 25020, headline: "CIRCULAR-SPORTS CARNIVAL FOR CONTRACTOR WORKERS- 23RD FEBRUARY 2025", href: "#" },
    { id: 25019, headline: "CIRCULAR-LIST OF PERSONNEL ENROLLED IN HINDI TEACHING SCHEME(SESSION JAN-MAY25)", href: "#" },
    { id: 25018, headline: "Circular for Selection of Badminton Players for DSP", href: "#" },
    { id: 25017, headline: "Circular SPSB Cricket", href: "#" },
    { id: 25016, headline: "CIRCULAR - DA REVISION", href: "#" },
    { id: 25015, headline: "Non-Submission of AIPR 2024", href: "#" },
    { id: 25014, headline: "Circular - Selection of Players for Volley Ball Team", href: "#" },
    { id: 25013, headline: "Circular - Selection of Coach for Volley Ball Team", href: "#" },
    { id: 25012, headline: "CIRCULAR-HEALTH CHECK-UP SCHEDULED FOR NON-EXECUTIVE EMPLOYEES (FEBRUARY-2025).pdf", href: "#" },
    { id: 25011, headline: "CIRCULAR- SUBMISSION FOR ANNUAL IMMOVABLE PROPERTY RETURN -2024", href: "#" },
    { id: 25010, headline: "Notice - Capturing of Biometrics for RFID of Contract Workers- Phase -3", href: "#" },
    { id: 25009, headline: "CIRCULAR - REVISION OF INCENTIVE SCHEME OF WHEEL AND AXLE PLANT UNDER RIS-2007", href: "#" },
    { id: 25008, headline: "CIRCULAR-LONG SERVICE AWARD-2025", href: "#" },
    { id: 25007, headline: "Circular for celebration of SAIL Foundation Day on 24th January-2025", href: "#" },
    { id: 25006, headline: "Circular Award-2024", href: "#" },
    { id: 25005, headline: "Notice for Contract Workers - Daily Rate of Wages w.e.f 01.01.2025", href: "#" },
    { id: 25004, headline: "CIRCULAR-DSP HINDI TEACHING SCHEME-SESSION (JAN-MAY-2025)", href: "#" },
    { id: 25003, headline: "CIRCULAR-SAIL GAURAV DIWAS", href: "#" },
    { id: 25002, headline: "CIRCULAR - HOLIDAYS AND LEAVES FOR CONTRACTOR WORKERS IN DSP -2025", href: "#" },
    { id: 25001, headline: "CIRCULAR-HOLIDAY LIST-2025", href: "#" }
  ],
  "2024": [
    { id: 24154, headline: "Notice for Contractor Workers - Revised GPAIS Premium Amount w.e.f 01.01.2025", href: "#" },
    { id: 24153, headline: "CIRCULAR - HOLIDAYS AND LEAVES FOR CONTRACTOR WORKERS IN DSP -2025", href: "#" },
    { id: 24152, headline: "CIRCULAR-HEALTH CHECK UP OF NON-EXECUTIVE EMPLOYEES DURING THE MONTH OF JANUARY-2025", href: "#" },
    { id: 24151, headline: "CIRCULAR-HOLIDAY LIST-2025", href: "#" },
    { id: 24150, headline: "Junior Manager Placement Order dated 12-12-2024", href: "#" },
    { id: 24149, headline: "CIRCULAR-SELECTION OF PLAYERS FOR DSP TABLE TENNIS TEAM", href: "#" },
    { id: 24148, headline: "Notice - Implementation of Biometric Attendance System for Contractor Workers", href: "#" },
    { id: 24147, headline: "Circular- Selection Trial for Inter Steel Football Championship-2024-25", href: "#" },
    { id: 24146, headline: "Notice - Football Coach for Inter Steel Football Championship -2024-25", href: "#" },
    { id: 24145, headline: "CIRCULAR-ZERO TOLERANCE SAFETY RULES (REVISED)", href: "#" },
    { id: 24144, headline: "CIRCULAR-HEALTH CHECK-UP FOR NON-EXECUTIVE EMPLOYEES DURING THE MONTH OF DECEMBER-2024", href: "#" },
    { id: 24143, headline: "CIRCULAR-SELECTION OF PLAYERS FOR DSP CRICKET TEAM", href: "#" },
    { id: 24142, headline: "CIRCULAR-SELECTION OF COACH FOR DSP CRICKET TEAM", href: "#" },
    { id: 24141, headline: "Notice for Contract Workers - Daily Rate of Wages w.e.f 01.07.2024", href: "#" },
    { id: 24140, headline: "CIRCULAR-DSP NATAK TEAM-ISPAT PARIDRISHYA", href: "#" },
    { id: 24139, headline: "CIRCULAR-GPAIS-BASIC RATE OF PREMIUM AND OPTION FOR EMPLOYEES", href: "#" },
    { id: 24138, headline: "Circular - Inter Department Table Tennis Tournament-2024", href: "#" },
    { id: 24137, headline: "Circular- Non-Executive Health Check up- November 2024", href: "#" },
    { id: 24136, headline: "CIRCULAR - DA REVISION", href: "#" },
    { id: 24135, headline: "APPEAL", href: "#" },
    { id: 24134, headline: "CIRCULAR- ONE DAY STRIKE ON 28-10-2024", href: "#" },
    { id: 24133, headline: "CIRCULAR-FELICITATING WARDS OF EMPLOYEES WHO HAVE REPRESE", href: "#" },
    { id: 24132, headline: "CIRCULAR-JAWAHAR AWARD, DICs EXCELLENCE AWARD AND JAWAHARLAL NEHRU GROUP AWARD FOR -2024", href: "#" },
    { id: 24131, headline: "CIRCULAR-GIFT CARD", href: "#" },
    { id: 24130, headline: "ONLINE TEST SCHEDULE FOR PROMOTION FROM E2 TO E3, E4 TO E5 & E6 TO E7 GRADE WEF 30-06-2025", href: "#" },
    { id: 24129, headline: "CIRCULAR-INTER DEPARTMENT BADMINTON TOURNAMENT-2024", href: "#" },
    { id: 24128, headline: "Circular- Nomination for Nehru Award 2024", href: "#" },
    { id: 24127, headline: "CIRCULAR-HEALTH CHECK -UP OF NON-EXECUTIVE EMPLOYEES-OCTOBER-2024", href: "#" },
    { id: 24126, headline: "CIRCULAR-MEDICLAIM SCHEME EXT.-4", href: "#" },
    { id: 24125, headline: "Notice for Contract Workers -Exercise to facilitate PF, ESI etc. settlement issues", href: "#" },
    { id: 24124, headline: "Internal Circular for filling-up positions at ICVL, Mozambique on deputation basis", href: "#" },
    { id: 24123, headline: "Internal Circular for filling up the position of Faculty Member in Academic Function at Management Training Institute (MTI), Ranchi", href: "#" },
    { id: 24122, headline: "Internal Circular for the post of Application Engineer at Central Marketing Organization", href: "#" },
    { id: 24121, headline: "Circular - Merit Award Scheme for Wards of Contractor Workers", href: "#" },
    { id: 24120, headline: "CIRCULAR- VISHWAKARMA PUJA-2024", href: "#" },
    { id: 24119, headline: "Circular- Rajbhasha Pakhwada -2024 -Programs (Revised)", href: "#" },
    { id: 24118, headline: "Dr. APJ Abdul Kalam H1 2024-25", href: "#" },
    { id: 24117, headline: "Circular- Non Executive Health Check-up", href: "#" },
    { id: 24116, headline: "Circular- Amendment in Leave Rules for Industrial Non-executive employees", href: "#" },
    { id: 24115, headline: "CIRCULAR- MEDICLAIM RENEWAL THIRD EXTENSION", href: "#" },
    { id: 24114, headline: "Notice for Contract Workers - Renewal of GPAIS for 24-25", href: "#" },
    { id: 24113, headline: "CIRCULAR- PUBLIC UTILITY SERVICE", href: "#" },
    { id: 24112, headline: "Individual Marks JM-2024", href: "#" },
    { id: 24111, headline: "CIRCULAR-EXTNSION DATE OF SAIL MEDICLAIM RENEWAL", href: "#" },
    { id: 24110, headline: "CIRCULAR- REVIEW OF MOTIVATIONAL SCHEME", href: "#" },
    { id: 24109, headline: "CIRCULAR- Completion of shift allocation and recording of attendance of Non Executives w.e.f. 01.09.2024", href: "#" },
    { id: 24108, headline: "List of employees appointed for the post of Junior Manager wef 30-06-2024", href: "#" },
    { id: 24107, headline: "CIRCULAR- OPTION FOR MEMBERSHIP OF THE NON-EXECUTIVE CLUB", href: "#" },
    { id: 24106, headline: "List of employees appointed for the post of Junior Manager wef 30-06-2024", href: "#" },
    { id: 24105, headline: "Redesignation of Junior Officer", href: "#" },
    { id: 24104, headline: "CIRCULAR-EXTENSION OF MEDICLAIM RENEWAL", href: "#" },
    { id: 24103, headline: "Reimbursement of Mobile Handsets for executives", href: "#" },
    { id: 24102, headline: "Circular - Premchand Jayanti Samaroh", href: "#" },
    { id: 24101, headline: "CIRCULAR- DA REVISION", href: "#" },
    { id: 24100, headline: "INTERVIEW SCHEDULE FOR E7-E8 GRADE PROMOTION WEF 30-06-2023", href: "#" },
    { id: 24099, headline: "CIRCULAR- Permission for acquiring Professional Qualification", href: "#" },
    { id: 24098, headline: "Circular-Recording of attendance for non-executiives through BAMS only w.e.f. 01.09.2024", href: "#" },
    { id: 24097, headline: "Empanelment of Retired Officers as Inquiry Officers", href: "#" },
    { id: 24096, headline: "JO Interview Schedule 2024", href: "#" },
    { id: 24095, headline: "Circular - Netaji Subhas Chandra Bose Excellence Award - 2024", href: "#" },
    { id: 24094, headline: "Circular- RENEWAL OF SAIL MEDICLAIM 2024-25", href: "#" },
    { id: 24093, headline: "Circular- Crash course on Yoga and Zumba", href: "#" },
    { id: 24092, headline: "Employees shortlisted for Interview for promotion from Non-Executive to Executive cadre (JO-2024)", href: "#" },
    { id: 24091, headline: "Circular- Extension of date for taking option from employees for GPAIS", href: "#" },
    { id: 24090, headline: "Promotion Order E1-E2, E2-E3, E3-E4 & E4-E5 dt. 30-06-2024", href: "#" },
    { id: 24089, headline: "Circular - DSP Hindi Teaching Scheme", href: "#" },
    { id: 24088, headline: "NOTICE - Application for Supplementary Leave in LMS", href: "#" },
    { id: 24087, headline: "CIRCULAR-Reimbursement for working in Night Shift", href: "#" },
    { id: 24086, headline: "CIRCULAR-DA REVISION", href: "#" },
    { id: 24085, headline: "Circular for observation of International Day of Yoga 2024", href: "#" },
    { id: 24084, headline: "Circular Option for Group Personal Accident Insurance Scheme from employees", href: "#" },
    { id: 24083, headline: "Circular- Final campaign for enrollment w.r.t. implementation of BAMS", href: "#" },
    { id: 24082, headline: "(E6-E7) Interview Schedule", href: "#" },
    { id: 24081, headline: "CIRCULAR- ONLINE MEDICAL BILL REIMBURSEMENT SYSTEM", href: "#" },
    { id: 24080, headline: "CIRCULAR-APPLICATION FOR OPERATING VARIOUS HEAVY VEHICLE EQUIPMENT", href: "#" },
    { id: 24079, headline: "INTERVIEW SCHEDULE FOR E5-E6 GRADE - 2024", href: "#" },
    { id: 24078, headline: "INTERVIEW SCHEDULE FOR E3-E4 GRADE - 2024", href: "#" },
    { id: 24077, headline: "Circular- General Guidelines on Biometric Attendance Management System", href: "#" },
    { id: 24076, headline: "JO Exam Spent On duty", href: "#" },
    { id: 24075, headline: "Revised Furniture Facility Scheme", href: "#" },
    { id: 24074, headline: "CIRCULAR-COUNSELLING CENTER DISHA AT T A BUILDING", href: "#" },
    { id: 24073, headline: "Renaming of Personnel and HRD departments", href: "#" },
    { id: 24072, headline: "Information Handout for JO Online Examination-2024", href: "#" },
    { id: 24071, headline: "Link for downloading the Admit Card for the JO examination - 2024", href: "#" },
    { id: 24070, headline: "Link for CBT practice test for JO-2024", href: "#" },
    { id: 24069, headline: "CIRCULAR- DISCIPLINE MANAGEMENT", href: "#" },
    { id: 24068, headline: "Circular- Biometric Attendance Management System-Trial Run for Non-executives", href: "#" },
    { id: 24067, headline: "Circular- Additional holiday in lieu of 14.04.2024(Sunday) 0001", href: "#" },
    { id: 24066, headline: "SAIL JO Manual 2024 - Industry & Company Awarness", href: "#" },
    { id: 24065, headline: "SAIL JO Manual 2024 - General Functional Management", href: "#" },
    { id: 24064, headline: "SAIL JO Manual 2024 - General Plant Awareness", href: "#" },
    { id: 24063, headline: "SAIL JO Manual 2024 - General Plant Operation Engg", href: "#" },
    { id: 24062, headline: "NOTICE - EXAMINATION FOR JO-2024", href: "#" },
    { id: 24061, headline: "CIRCULAR-GENERAL ELECTION -2024 (CONTRACTOR WORKERS)", href: "#" },
    { id: 24060, headline: "REVISED-CIRCULAR MEDICINE ISSUE-2024", href: "#" },
    { id: 24059, headline: "CIRCULAR-MODULES LAUNCHED ON PM-DAKSH-DEPwD FOR PWDs", href: "#" },
    { id: 24058, headline: "Circular- Lok Sabha General Election - 2024", href: "#" },
    { id: 24057, headline: "CIRCULAR-NURTURING A CULTURE OF LEARNING AND DEVELOPMENT IN SAIL", href: "#" },
    { id: 24056, headline: "Circular- DSP Day Celebration on 24.04.204 at Nehru Stadium", href: "#" },
    { id: 24055, headline: "CIRCULAR-CLOSED HOLIDAY ON 14.04.2024", href: "#" },
    { id: 24054, headline: "CIRCULAR-MEDICINE-ISSUE-LP-COUNTER", href: "#" },
    { id: 24053, headline: "Circular - Closed Holiday on 14.04.2024 - For Contractor Workers", href: "#" },
    { id: 24052, headline: "CIRCULAR-ENROLLMENT OF CONTACTLESS ATTENDANCE SYSTEM FOR NON-EXECUTIVE EMPLOYEES", href: "#" },
    { id: 24051, headline: "CIRCULAR FOR MODEL CODE OF CONDUCT FOR LOK SABHA ELECTION-2024", href: "#" },
    { id: 24049, headline: "List of designated personnel officers for JO-2024", href: "#" },
    { id: 24048, headline: "Link for applictaion for JO-2024", href: "#" },
    { id: 24047, headline: "Circular- for Contract Workers- Reimbursement of revised AWA", href: "#" },
    { id: 24046, headline: "Notice for Contract Workers - Daily Rate of Wages w.e.f 01.03.2024", href: "#" },
    { id: 24045, headline: "Circular-Gate Pass No.-13 w.e.f. 01.05.2024", href: "#" },
    { id: 24044, headline: "Circular - Junior Officer (JO) -2024", href: "#" },
    { id: 24043, headline: "ONLINE PERFORMANCE APPRAISAL SYSTEM FOR NON EXECUTIVE EMPLOYEES", href: "#" },
    { id: 24042, headline: "CIRCULAR FOR SELECTION OF PLAYERS FOR CRICKET", href: "#" },
    { id: 24041, headline: "Circular - Compliance Checking through SAP", href: "#" },
    { id: 24040, headline: "CIRCULAR FOR SELECTION OF PLAYERS FOR BASKETBALL", href: "#" },
    { id: 24039, headline: "NOTICE FOR SELECTION OF COACH FOR BASKETBALL", href: "#" },
    { id: 24038, headline: "CIRCULAR-AMENDMENT IN INCENTIVE SCHEME FOR ACQUIRING PROFESSIONAL QUALIFICATION", href: "#" },
    { id: 24037, headline: "Revised Circular for selection of players for Table Tennis", href: "#" },
    { id: 24036, headline: "Circular for selection of players for Table Tennis", href: "#" },
    { id: 24035, headline: "Notice for Selection of coach for Table Tennis", href: "#" },
    { id: 24034, headline: "Circular for selection of players for Boxing", href: "#" },
    { id: 24033, headline: "Notice for Selection of coach for Boxing", href: "#" },
    { id: 24032, headline: "Payment of advance", href: "#" },
    { id: 24031, headline: "CIRCULAR-CELEBRATION OF INTERNATIONAL WOMENS DAY", href: "#" },
    { id: 24030, headline: "CIRCULAR-PUBLIC UTILITY SERVICE", href: "#" },
    { id: 24029, headline: "Link for SAIL เคถเคพเคฌเคพเคถ (Shabash) Scheme", href: "#" },
    { id: 24028, headline: "CIRCULAR-MEAL CARD", href: "#" },
    { id: 24027, headline: "Selection for the post of Director-In-Charge (Rourkela Steel Plant), SAIL", href: "#" },
    { id: 24026, headline: "CIRCULAR-EXTENSION OF DATE FOR GIFT CARD", href: "#" },
    { id: 24025, headline: "CIRCULAR FOR OPERATION OF BADMINTON COURT", href: "#" },
    { id: 24024, headline: "Revised Cricular for selection of players for Kabaddi", href: "#" },
    { id: 24023, headline: "Biometric Attendance Management System dashboard familiarization and related issues", href: "#" },
    { id: 24022, headline: "Circular -D.O.B Correction Exercise for Contractor Workers", href: "#" },
    { id: 24021, headline: "Notice - Selection of Coach for SPSB Kabaddi Champioship", href: "#" },
    { id: 24020, headline: "Circular - Selection of players for SPSB Kabaddi Champioship", href: "#" },
    { id: 24019, headline: "Notice - Selection of Coach for SPSB Football Champioship", href: "#" },
    { id: 24018, headline: "Circular - Selection of players for SPSB Football Championship", href: "#" },
    { id: 24017, headline: "CIRCULAR -HALFDAY HOLIDAY FOR CONTRACTOR WORKER", href: "#" },
    { id: 24016, headline: "CIRCULAR FOR HALFDAY HOLIDAY FOR REGULAR EMPLOYEES", href: "#" },
    { id: 24015, headline: "List of Jawahar, DICs Excellence & Jawaharlal Nehru Group Awardees - 2023", href: "#" },
    { id: 24014, headline: "FINAL CIRCULAR- LSA-2024", href: "#" },
    { id: 24013, headline: "CIRCULAR FOR SAIL DAY -2024", href: "#" },
    { id: 24012, headline: "CIRCULAR- DA REVISION", href: "#" },
    { id: 24011, headline: "CIRCULAR- GIFT CARD (E-CARD)", href: "#" },
    { id: 24010, headline: "CIRCULAR-SELECTION FOR VOLLEYBALL PLAYERS", href: "#" },
    { id: 24009, headline: "LONG SERVICE AWARDEES-2024, FINAL LIST", href: "#" },
    { id: 24008, headline: "CIRCULAR-LMS-2024", href: "#" },
    { id: 24007, headline: "Revised Rules for Promotion from Non-Executive to Executive cadre", href: "#" },
    { id: 24006, headline: "Selection for the post of CMD RINL", href: "#" },
    { id: 24005, headline: "Notice for Contract Workers - Daily Rate of Wages w.e.f 01.01.2024 (including Non- Works)", href: "#" },
    { id: 24004, headline: "Circular - List of candidates for Hindi Teaching Scheme - 2024", href: "#" },
    { id: 24003, headline: "CIRCULAR- ENROLLMENT OF NON-EXECUTIVES FOR CONTACTLESS ATTENDANCE SYSTEM", href: "#" },
    { id: 24002, headline: "Circular - Holidays and Leaves for Contractor Workers in DSP - 2024", href: "#" },
    { id: 24001, headline: "CIRCULAR-HOLIDAY LIST FOR EMPLOYEES OF DSP-2024", href: "#" }
  ],
  "2023": [
    { id: 23137, headline: "Promotion Order E1-E2 dt 30-12-2023", href: "#" },
    { id: 23136, headline: "Circular - Application from SAIL Executives for LinkedIn membership", href: "#" },
    { id: 23135, headline: "Circular - Holidays and Leaves for Contractor Workers in DSP - 2024", href: "#" },
    { id: 23134, headline: "CIRCULAR- IMPLEMENTATION OF CONTACTLESS ATTENDANCE SYSTEM", href: "#" },
    { id: 23133, headline: "Circular for selction of employees for badminton", href: "#" },
    { id: 23132, headline: "CIRCULAR-HOLIDAY LIST FOR EMPLOYEES OF DSP-2024", href: "#" },
    { id: 23131, headline: "Circular for Gate Pass No.-13 (valid from 01.01.2024 to 31.03.2024)", href: "#" },
    { id: 23130, headline: "Notice for Contract Workers - Daily Rate of Wages w.e.f 01.01.2024 (excluding Non-Works)", href: "#" },
    { id: 23129, headline: "Circular -Inter Department Volleyball Tournament 2023", href: "#" },
    { id: 23128, headline: "PF of Junior Officers of 2008 and 2010 batches", href: "#" },
    { id: 23127, headline: "Circular - DSP Hindi Teaching Scheme", href: "#" },
    { id: 23126, headline: "NOTICE - SELECTION OF COACH FOR INTER STEEL CHESS CHAMPIONSHIP 2023-24", href: "#" },
    { id: 23125, headline: "CIRCULAR- SELECTION OF PLAYERS FOR INTER STEEL CHESS CHAMPIONSHIP 2023-24", href: "#" },
    { id: 23124, headline: "CIRCULAR- ONLINE SURVEY ON SAIL-VISION STATEMENT", href: "#" },
    { id: 23123, headline: "CIRCULAR- DATA FOR FUTURE SKILL PRIME PORTAL", href: "#" },
    { id: 23122, headline: "CIRCULAR- AMR KATHA DICR SANGE", href: "#" },
    { id: 23121, headline: "CIRCULAR- ONLINE VEHICLE PASS SYSTEM", href: "#" },
    { id: 23120, headline: "Ammendment Circular for selection of players for Badminton", href: "#" },
    { id: 23119, headline: "NOTICE & CIRCULAR FOR INTER STEEL PLANT BADMINTON CHAMPIONSHIP 2023-24", href: "#" },
    { id: 23118, headline: "NOTICE & CIRCULAR FOR INTER STEEL PLANT CRICKET CHAMPIONSHIP 2023-24", href: "#" },
    { id: 23117, headline: "Application for the post of Director, NISST - Extension of last date", href: "#" },
    { id: 23116, headline: "Vacancy Notice for General Manager (General) E7 for HR on deputation basis in Central Warehousing Corporation", href: "#" },
    { id: 23115, headline: "CIRCULAR- AIR TICKET BOOKING FOR OFFICIAL TOUR", href: "#" },
    { id: 23114, headline: "CRCULAR- ADDITIONAL TRANSPORT ALLOWANCE TO DIVYANGJAN", href: "#" },
    { id: 23113, headline: "CIRCULAR -SAIL ANNUAL INCREMENT RULES", href: "#" },
    { id: 23112, headline: "CIRCULAR-FORMAT FOR MEDICAL INVALIDATION", href: "#" },
    { id: 23111, headline: "Advertisement for the post of Director, National Institute of Secondary Steel Technology (NISST), Mandi Gobindgarh, Punjab", href: "#" },
    { id: 23110, headline: "CIRCULAR- FIT INDIA RUN-2023", href: "#" },
    { id: 23109, headline: "CIRCULAR-IMPLEMENTATION OF CONTACTLESS ATTENDANCE SYSTEM", href: "#" },
    { id: 23108, headline: "New EPMS Link", href: "#" },
    { id: 23107, headline: "CIRCULAR -DA REVISION", href: "#" },
    { id: 23106, headline: "Jawahar Award, DICs Excellence Award & Jawaharlal Nehru Group Award for the year 2023", href: "#" },
    { id: 23105, headline: "Scheme-SAIL Corporate Awards for Excellence-2023", href: "#" },
    { id: 23104, headline: "Notice for Contractor Employees - Introduction of GPAIS", href: "#" },
    { id: 23103, headline: "CIRCULAR-SAIL शाबाश Scheme", href: "#" },
    { id: 23102, headline: "CIRCULAR- NOMINATION FOR NEHRU AWARD-2023", href: "#" },
    { id: 23101, headline: "CIRCULAR-GATEPASS -13", href: "#" },
    { id: 23100, headline: "ONLINE TEST SCHEDULE FOR PROMOTION FROM E4 TO E5 & E6 TO E7 GRADE WEF 30-06-2024", href: "#" },
    { id: 23099, headline: "CIRCULAR- INTER DEPARTMENT NIGHT FOOTBALL TOURNAMENT", href: "#" },
    { id: 23098, headline: "CIRCULAR-DSP MUSICAL BAND-ISPAT ER SHUR", href: "#" },
    { id: 23097, headline: "CIRCULAR-ZERO TOLERANCE SAFETY RULES", href: "#" },
    { id: 23096, headline: "CIRCULAR-CONTACTLESS ATTENDANCE SYSTEM & RFID CARD", href: "#" },
    { id: 23095, headline: "Circular Selection of players for Volleyball", href: "#" },
    { id: 23094, headline: "Circular-Selection of coach for Volleyball", href: "#" },
    { id: 23093, headline: "CIRCULAR-VISHWAKARMA PUJA-2023", href: "#" },
    { id: 23092, headline: "CIRCULAR-MERIT CUM MEANS SCHOLARSHIP", href: "#" },
    { id: 23091, headline: "CIRCULAR-SCHOLARSHIP FOR HANDICAPPED CHILDREN", href: "#" },
    { id: 23090, headline: "परिपत्र - राजभाषा पखवाड़ा-2023", href: "#" },
    { id: 23089, headline: "CIRCULAR-SAIL MEDICLAIM- EXTENSION OF DUE DATE FOR RENEWAL", href: "#" },
    { id: 23088, headline: "CIRCULAR-UNAUTHORIZED COMMUNICATION", href: "#" },
    { id: 23087, headline: "Phd program in CSIR-CMERI", href: "#" },
    { id: 23086, headline: "CIRCULAR-CONTACTLESS ATTENDANCE SYSTEM & RFID CARD", href: "#" },
    { id: 23085, headline: "CIRCULAR- SAIL MEDICLAIM - EXTENSION OF DUE DATE FOR RENEWAL", href: "#" },
    { id: 23084, headline: "CIRCULAR-PUBLIC UTILITY SERVICE", href: "#" },
    { id: 23083, headline: "CIRCULAR-ONLINE TRACKING SYSTEM FOR MEDICAL BILL REIMBURSEMENT", href: "#" },
    { id: 23082, headline: "CIRCULAR- MERI MAATI MERA DESH", href: "#" },
    { id: 23081, headline: "CIRCULAR-HAR GHAR TIRANGA", href: "#" },
    { id: 23080, headline: "Notice for Contractor Workers - Daily Wages w.e.f 01.07.2023 (including Non-Works)", href: "#" },
    { id: 23079, headline: "CIRCULAR- OPERATION OF YOGA CLASS", href: "#" },
    { id: 23078, headline: "Circular - Netaji Subhas Chandra Bose Excellence Award - 2023", href: "#" },
    { id: 23077, headline: "CIRCULAR- HINDI SHIKSHAN YOJNA", href: "#" },
    { id: 23076, headline: "Circular - Premchand Jayanti Samaroh", href: "#" },
    { id: 23075, headline: "CIRCULAR - PAYMENT GATEWAY FOR MEDICLAIM", href: "#" },
    { id: 23074, headline: "Circular - Hindi Teaching Scheme-2023", href: "#" },
    { id: 23073, headline: "CIRCULAR-RENEWAL OF SAIL MEDICLAIM (2023-24)", href: "#" },
    { id: 23072, headline: "Circular- Updation of Date of Birth of dependents for medical purpose and Revised Annexure-B", href: "#" },
    { id: 23071, headline: "Circular- Panchayat General Elections 2023", href: "#" },
    { id: 23070, headline: "NOTICE for Contractor Workers - Daily Wages w.e.f 01.07.2023", href: "#" },
    { id: 23069, headline: "Circular- Implementation of Contactless Attendance System", href: "#" },
    { id: 23068, headline: "Promotion Order E1-E2, E2-E3, E3-E4 & E4-E5 dt. 30-06-2023", href: "#" },
    { id: 23067, headline: "CIRCULAR-GATE PASS NO.13", href: "#" },
    { id: 23066, headline: "CIRCULAR - INTERNATIONAL YOGA DAY- 21st JUNE, 2023", href: "#" },
    { id: 23065, headline: "CIRCULAR- DISPOSAL OF RECORDS", href: "#" },
    { id: 23064, headline: "Notice regarding Individual marks JO 2022", href: "#" },
    { id: 23063, headline: "Circular- Permission for acquiring Professional Qualification", href: "#" },
    { id: 23062, headline: "INTERVIEW SCHEDULE FOR E6-E7 GRADE - 2023", href: "#" },
    { id: 23061, headline: "INTERVIEW SCHEDULE FOR E5-E6 GRADE - 2023", href: "#" },
    { id: 23060, headline: "INTERVIEW SCHEDULE FOR E3-E4 GRADE - 2023", href: "#" },
    { id: 23059, headline: "List of employees appointed for the post of JO wef 30-06-2022", href: "#" },
    { id: 23058, headline: "Notice - For Contractor Workers - Correction in Father’s Name - Husband’s Name", href: "#" },
    { id: 23057, headline: "Circular- Discontinuance of Company Facilities to ex-employees unauthorizedly residing in Company’s accommodation", href: "#" },
    { id: 23056, headline: "CIRCULAR- TIMEFRAME FOR MEDICAL BILL SIGNING", href: "#" },
    { id: 23055, headline: "JO interview schedule 2023", href: "#" },
    { id: 23054, headline: "CIRCULAR- GUIDELINES FOR EPS-95", href: "#" },
    { id: 23053, headline: "CIRCULAR- Submission of Joint Option for availing higher Pension under EPS-95", href: "#" },
    { id: 23052, headline: "CIRCULAR- DA REVISION", href: "#" },
    { id: 23051, headline: "Employees shortlisted for Interview for promotion from Non-Executive to Executive cadre (JO-2022)", href: "#" },
    { id: 23050, headline: "Circular - Closed Holiday on 14.04.2023 (For Contractor Workers)", href: "#" },
    { id: 23049, headline: "CIRCULAR-CLOSED HOLIDAY ON 14.04.2023", href: "#" },
    { id: 23048, headline: "CIRCULAR- POLICY INITIATIVES FOR ENABLING WOMEN EMPOWERMENT IN SAIL", href: "#" },
    { id: 23047, headline: "CIRCULAR- AMENDMENT IN POLICY FOR FORWARDING OF APPLICATIONS FOR OUTSIDE EMPLOYMENT", href: "#" },
    { id: 23046, headline: "CIRCULAR- AMENDMENTS IN SHORTER WORKING PERIOD SCHEME", href: "#" },
    { id: 23045, headline: "CIRCULAR-GUIDELINES FOR AVAILING TAX EXEMPTION FOR LTC", href: "#" },
    { id: 23044, headline: "Guidelines for self-appraisal under EPMS by below-Board level executives at the time of separation", href: "#" },
    { id: 23043, headline: "REVISED CIRCULAR- OPERATION OF NEW MULTI GYM", href: "#" },
    { id: 23042, headline: "CIRCULAR-Submission of Joint Option Under EPS-95", href: "#" },
    { id: 23041, headline: "CIRCULAR- MEDICAL ATTENDANCE & TREATMENT RULES", href: "#" },
    { id: 23040, headline: "Information Handout for JO Online Examination", href: "#" },
    { id: 23039, headline: "JO Admit Card", href: "#" },
    { id: 23038, headline: "CIRCULAR-Selection of Coach for Volleyball", href: "#" },
    { id: 23037, headline: "CIRCULAR-Selection of Coach for Basketball", href: "#" },
    { id: 23036, headline: "CIRCULAR-Selection of Coach for Athletics", href: "#" },
    { id: 23035, headline: "CIRCULAR - Selection of Players for SPSB Volleyball", href: "#" },
    { id: 23034, headline: "CIRCULAR- Selection of Players for SPSB Athletics", href: "#" },
    { id: 23033, headline: "CIRCULAR- Selection of Players for SPSB Basketball", href: "#" },
    { id: 23032, headline: "CIRCULAR - OPERATION OF NEW MULTI GYM", href: "#" },
    { id: 23031, headline: "Internal Circular issued by ICVL for the post of MD & CEO, ICVL, Mozambique", href: "#" },
    { id: 23030, headline: "Filling up of posts in National Commission for Protection of Child Rights", href: "#" },
    { id: 23029, headline: "Circular-Instructions by EPFO regarding submission of JOF for availing higher Pension under EPS-95", href: "#" },
    { id: 23028, headline: "Information for CBT practice test for JO", href: "#" },
    { id: 23027, headline: "CIRCULAR - GATE PASS NO.-13", href: "#" },
    { id: 23026, headline: "Practice test link for Re-examination of JO-2022", href: "#" },
    { id: 23025, headline: "Circular WomenDay - 2023", href: "#" },
    { id: 23024, headline: "CIRCULAR-PUBLIC UTILITY SERVICES", href: "#" },
    { id: 23023, headline: "Re-examination of JO-2022", href: "#" },
    { id: 23022, headline: "Circular -Extension of date & Submission of JOF by spouse of the deceased employee under EPS-95", href: "#" },
    { id: 23021, headline: "Circular - Mutual Family Benefit Scheme", href: "#" },
    { id: 23020, headline: "ONLINE TEST SCHEDULE FOR PROMOTION FROM E2 TO E3, E4 TO E5 & E6 TO E7 GRADE WEF 30-06-2023", href: "#" },
    { id: 23019, headline: "Circular - Submission of Jt. Option Form under EPS 95", href: "#" },
    { id: 23018, headline: "Circular- Selection of players for SPSB Kabaddi championship", href: "#" },
    { id: 23017, headline: "Notice - Selection of coach for Kabaddi", href: "#" },
    { id: 23016, headline: "Durgapur Steel Plant Employees Mutual Family Benefit Scheme (Voluntary)", href: "#" },
    { id: 23015, headline: "Circular - Judgement of Supreme Court on EPS-95", href: "#" },
    { id: 23014, headline: "INTERVIEW SCHEDULE FOR E7-E8 GRADE WEF 30-06-2022", href: "#" },
    { id: 23013, headline: "Winners of Nehru and Dr. B.R. Ambedkar Suggestion Award -2022", href: "#" },
    { id: 23012, headline: "Circular - SAIL DAY-2023", href: "#" },
    { id: 23011, headline: "List of Jawahar, DICs Excellence & Jawaharlal Nehru Group Awardees - 2022", href: "#" },
    { id: 23010, headline: "Circular - Selection of players for SPSB cricket tournament", href: "#" },
    { id: 23009, headline: "Notice - Selection of coach for SPSB cricket tournament", href: "#" },
    { id: 23008, headline: "CIRCULAR - LSA - 2023", href: "#" },
    { id: 23007, headline: "Online ADC Schedule for E6 grade", href: "#" },
    { id: 23006, headline: "Circular- D.A Revision", href: "#" },
    { id: 23005, headline: "Circular - Medical Referral", href: "#" },
    { id: 23004, headline: "Notice for Contract Workers- Daily Wages with effect from 01.01.2023.", href: "#" },
    { id: 23003, headline: "Long Service Awardees - 2023 - Final List", href: "#" },
    { id: 23002, headline: "Circular-Holidays & Leaves for contract workers engaged by contractors for the year 2023", href: "#" },
    { id: 23001, headline: "Circular-Holiday List - 2023", href: "#" }
  ],
  "2022": [
    { id: 22138, headline: "Circular-Holidays & Leaves for contract workers engaged by contractors for the year 2023", href: "#" },
    { id: 22137, headline: "Circular - Selection of players for SAIL Swarna Jayanti Volleyball Tournament 2022", href: "#" },
    { id: 22136, headline: "Scheme for Sponsoring Executives for Higher Specialized EducationTraining", href: "#" },
    { id: 22135, headline: "Circular - Leave Management System (LMS)", href: "#" },
    { id: 22134, headline: "Circular-Holiday List - 2023", href: "#" },
    { id: 22133, headline: "Circular - Rules for Retention of Company Accomodation by Ex-employees at City Locations", href: "#" },
    { id: 22132, headline: "Internal Circular dated 23.12.2022 for posting at Salem Steel Plant", href: "#" },
    { id: 22131, headline: "Notice for cancellation of JO written examination", href: "#" },
    { id: 22130, headline: "Interview Schedule for JO-2022", href: "#" },
    { id: 22129, headline: "Circular- Selection trial for Inter Steel Plant Football Championship 2022-23", href: "#" },
    { id: 22128, headline: "Cricular- Selection of Coach for Inter Steel Plant Football Championship", href: "#" },
    { id: 22127, headline: "Circular - Motivational Award Schemes of DSP", href: "#" },
    { id: 22126, headline: "JO - Shortlisted for Interview", href: "#" },
    { id: 22125, headline: "Circular - Online Employee Grievance Redressal System", href: "#" },
    { id: 22124, headline: "Cricular - Selection Trial for Inter Steel Plant Badminton Championship 2022-23", href: "#" },
    { id: 22123, headline: "Circular - GPAIS Extension 2022-23", href: "#" },
    { id: 22122, headline: "Circular - Extension of last date for Inter Deptt. Chess Tournament", href: "#" },
    { id: 22121, headline: "Circular - Merit cum Means Scholarship", href: "#" },
    { id: 22120, headline: "Circular - Scholarship for Handicapped Children", href: "#" },
    { id: 22119, headline: "Circular - Regn. for Voluntary Blood Donation", href: "#" },
    { id: 22118, headline: "Vacancy - Position of Director, Biju Patnaik National Steel Institute (BPNSI)", href: "#" },
    { id: 22117, headline: "Circular - Inter Department Chess Tournament - 2022", href: "#" },
    { id: 22116, headline: "Circular - Gift Card", href: "#" },
    { id: 22115, headline: "Internal Circular - Manpower Requirement at ICVL, Mozambique", href: "#" },
    { id: 22114, headline: "Circular -Statutory Compliance Clearance", href: "#" },
    { id: 22113, headline: "Circular - Selection Trial for SAIL Swarna Jayanti Football tournament for Men", href: "#" },
    { id: 22112, headline: "Vacancy - Position of Chairman, SAIL", href: "#" },
    { id: 22111, headline: "Circular - Run for Unity 2022", href: "#" },
    { id: 22110, headline: "Notice for Admit Card for JO", href: "#" },
    { id: 22109, headline: "Circular - Nehru Award - 2022", href: "#" },
    { id: 22108, headline: "DICs Excellence, Jawahar Award & Jawaharlal Nehru Group Award for the year 2022", href: "#" },
    { id: 22107, headline: "Circular -Swarna Jayanti Table Tennis Championship - Selection Trial", href: "#" },
    { id: 22106, headline: "Circular -D.A Revision", href: "#" },
    { id: 22105, headline: "Circular - Extension of date for SAIL Corporate Awards for Excellence - 2022", href: "#" },
    { id: 22104, headline: "Leave and Tour Approval", href: "#" },
    { id: 22103, headline: "Important Notification - JO", href: "#" },
    { id: 22102, headline: "Timelines for Mid-year Review under EPMS for the year 2022-23", href: "#" },
    { id: 22101, headline: "Strict adherence to clause 17.0 & 17(A) of the SAIL CDA Rules", href: "#" },
    { id: 22100, headline: "Extension of last date for Internal Circular for posting in Law Department(s)", href: "#" },
    { id: 22099, headline: "Circular - JO 2022-Extension of last date for application", href: "#" },
    { id: 22098, headline: "Circular - SAIL Corporate Awards for Excellence -2022", href: "#" },
    { id: 22097, headline: "Vacancy for the post of Chairman, DVC", href: "#" },
    { id: 22096, headline: "परिपत्र- राजभाषा पखवाड़ा – 2022", href: "#" },
    { id: 22095, headline: "Circular-Distribution of Mementos to SAIL employees", href: "#" },
    { id: 22094, headline: "List of designated personnel officers for JO-2022", href: "#" },
    { id: 22093, headline: "Circular- Vishwakarma Puja-2022", href: "#" },
    { id: 22092, headline: "Internal Circular for posting in Law Department(s)", href: "#" },
    { id: 22091, headline: "Circular - Junior Officer (JO) -2022", href: "#" },
    { id: 22090, headline: "Circular - Gate Pass-13 - Sept,2022 to Feb,2023", href: "#" },
    { id: 22089, headline: "DSP JO Manual 2022 - Revised Plant Specific Manual", href: "#" },
    { id: 22088, headline: "Circular- Gift declaration Form Under Clause 12 of SAIL-CDA Rule 1977", href: "#" },
    { id: 22087, headline: "Extension of date for participation Inter Department Volleyball Tournament -2022", href: "#" },
    { id: 22086, headline: "SAIL JO Manual 2022 - Industry & Company Awarness", href: "#" },
    { id: 22085, headline: "SAIL JO Manual 2022 - General Functional Management", href: "#" },
    { id: 22084, headline: "SAIL JO Manual 2022 - General Plant Awareness", href: "#" },
    { id: 22083, headline: "SAIL JO Manual 2022 - General Plant Operation Engg", href: "#" },
    { id: 22082, headline: "Circular - SAIL Mediclaim- Extn. of due date for Renewal", href: "#" },
    { id: 22081, headline: "Circular - Inter Department Volleyball Tournament - 2022", href: "#" },
    { id: 22080, headline: "Circular - SAIL Mediclaim- Extension of due date for Renewal", href: "#" },
    { id: 22079, headline: "Circular - Perks-Allowances for Non- executive employees", href: "#" },
    { id: 22078, headline: "Circular - Har Ghar Tiranga", href: "#" },
    { id: 22077, headline: "Circular -Badminton Championship", href: "#" },
    { id: 22076, headline: "Notice for Contract Workers w.r.t VDA", href: "#" },
    { id: 22075, headline: "Circular - Renewal of SAIL Mediclaim for ex-employees", href: "#" },
    { id: 22074, headline: "Circular on DA Revision", href: "#" },
    { id: 22073, headline: "Circular for Walk or Run - with route map", href: "#" },
    { id: 22072, headline: "Circular - Revision of SAIL Pension Scheme for Employees of SAIL", href: "#" },
    { id: 22071, headline: "Circular - Revised Policy and Rules for promotion from Non-executive to Executive cadre", href: "#" },
    { id: 22070, headline: "Circular - Guidelines for dealing with Compassionate Cases", href: "#" },
    { id: 22069, headline: "Notice for Contract Workers w.r.t VDA", href: "#" },
    { id: 22068, headline: "Promotion Orders E6-E7 dt. 30-06-2022", href: "#" },
    { id: 22067, headline: "Promotion Order E5-E6 dt. 30-06-2022", href: "#" },
    { id: 22066, headline: "Promotion Order E1-E2, E2-E3, E3-E4 & E4-E5 dt. 30-06-2022", href: "#" },
    { id: 22065, headline: "Circular - Bar coding of FMTE Booklets", href: "#" },
    { id: 22064, headline: "Circular - Requirement of staff for Rajbhasha Vibhag, DSP", href: "#" },
    { id: 22063, headline: "Circular - Boiler Operator", href: "#" },
    { id: 22062, headline: "Circular - Internation Day of Yoga 2022", href: "#" },
    { id: 22061, headline: "Circular - Inviting applications for operating Light Commercial Vehicle", href: "#" },
    { id: 22060, headline: "Scholarship for handicapped children of regualr employees", href: "#" },
    { id: 22059, headline: "Merit & Merit cum Means Scholarship for children of regular employees", href: "#" },
    { id: 22058, headline: "Interview Schedule for E6 to E7 grade - 2022", href: "#" },
    { id: 22057, headline: "Interview Schedule for E5 to E6 grade - 2022", href: "#" },
    { id: 22056, headline: "CIRCULAR - REQUIREMENT - OPRN. OF HEAVY VEHICLE EQUIPMENT FOR PLANT GARAGE DEPTT", href: "#" },
    { id: 22055, headline: "Interview Schedule for E3 to E4 grade - 2022", href: "#" },
    { id: 22054, headline: "Vacancy for post of Director (Technical), NMDC Ltd.", href: "#" },
    { id: 22053, headline: "Vacancy for post of Director (Finance), KIOCL", href: "#" },
    { id: 22052, headline: "Circular - Clarification-Correction in the name of Family members of employees", href: "#" },
    { id: 22051, headline: "Circular - Transport Subsidy to Orthopaedically Handicapped, Blind, Deaf and Dumb employees in Non-executive grades", href: "#" },
    { id: 22050, headline: "Circular - Inter Department Cricket - 2022", href: "#" },
    { id: 22049, headline: "Circular for Gate Pass-13", href: "#" },
    { id: 22048, headline: "Circular - DA Revision", href: "#" },
    { id: 22047, headline: "Circular - Visiting Card for Executives", href: "#" },
    { id: 22046, headline: "Circular - Closed Holiday on 14.04.2022 - For Contract Workers", href: "#" },
    { id: 22045, headline: "Circular - Closed Holiday on 14.04.2022", href: "#" },
    { id: 22044, headline: "Circular - Asansol Bye-election - for Contract Workers", href: "#" },
    { id: 22043, headline: "Circular - Asansol Bye-election", href: "#" },
    { id: 22042, headline: "Circular - Meal Card", href: "#" },
    { id: 22041, headline: "An Appeal regarding strike on 28.03.2022 and 29.03.2022 (Hindi)", href: "#" },
    { id: 22040, headline: "An Appeal regarding Strike on 28.03.2022 and 29.03.2022", href: "#" },
    { id: 22039, headline: "Circular on EPMS Timelines", href: "#" },
    { id: 22038, headline: "Circular-Guidelines for employees regarding Covid-19 Management", href: "#" },
    { id: 22037, headline: "Circular - Strike on 28.03.2022 & 29.03.2022", href: "#" },
    { id: 22036, headline: "Circular - Selection of players for hockey", href: "#" },
    { id: 22035, headline: "Notice - Selection of coach for hockey", href: "#" },
    { id: 22034, headline: "Circular - Selection of players for volleyball", href: "#" },
    { id: 22033, headline: "Notice - Selection of coach for volleyball", href: "#" },
    { id: 22032, headline: "Circular - Vehicle Pass for Contractor Workers", href: "#" },
    { id: 22031, headline: "Circular - Badminton tournament for female employees on womens day", href: "#" },
    { id: 22030, headline: "Circular Policy & Rules for promotion from Non-executive to Executive cadre (Junior Officer)", href: "#" },
    { id: 22029, headline: "Circular-Rules for Retention of Facilities on Transfer dated 19.02.2022", href: "#" },
    { id: 22028, headline: "Circular - Public Utility Services", href: "#" },
    { id: 22027, headline: "Circular - Selection of players for Football", href: "#" },
    { id: 22026, headline: "Circular - Revised SAIL TA Rules 2021", href: "#" },
    { id: 22025, headline: "Circular - Gate Pass - 13", href: "#" },
    { id: 22024, headline: "CIRCULAR - SELECTION OF PLAYERS FOR CRICKET", href: "#" },
    { id: 22023, headline: "NOTICE - SELECTION OF COACH FOR CRICKET", href: "#" },
    { id: 22022, headline: "Circular - Election under Asansol Municipal Corporation - 2022", href: "#" },
    { id: 22021, headline: "Requirement in National Film Development Corporation Limited (NFDC)", href: "#" },
    { id: 22020, headline: "Revised SAIL CDA Rules, 1977", href: "#" },
    { id: 22019, headline: "Internal Circular - Manpower Requirement at SSP", href: "#" },
    { id: 22018, headline: "Wage Notice for Contract Workers w. e. f 01.01.2022", href: "#" },
    { id: 22017, headline: "Internal Circular - Manpower Requirement at ICVL, Mozambique", href: "#" },
    { id: 22016, headline: "Vacancy for post of CMD, HMT Limited, Bengaluru", href: "#" },
    { id: 22015, headline: "Online Assessment & Development Centre (ADC) Schedule", href: "#" },
    { id: 22014, headline: "Circular - Revised Uniform Dress Code for Executives", href: "#" },
    { id: 22013, headline: "Circular - D.A Revision", href: "#" },
    { id: 22012, headline: "CIRCULAR - LSA-2022", href: "#" },
    { id: 22011, headline: "Wage Notice for Contract Workers of Works, Projects and TS(Elec) w. e. from 01.01.2022.", href: "#" },
    { id: 22010, headline: "Revision of Perks, Allowances for executives of SAIL (FY 2021-22)", href: "#" },
    { id: 22009, headline: "Long Service Awardees - 2022 - Final List", href: "#" },
    { id: 22008, headline: "Circular - COVID19 Guidelines for Employees", href: "#" },
    { id: 22007, headline: "Appeal (English) regarding strike on 05.01.2022", href: "#" },
    { id: 22006, headline: "Appeal (Hindi) regarding strike on 05.01.2022", href: "#" },
    { id: 22005, headline: "Notice - Selection of players for Hockey", href: "#" },
    { id: 22004, headline: "Holiday list of Contract Workers - 2022", href: "#" },
    { id: 22003, headline: "Notice - Selection of coach for Hockey", href: "#" },
    { id: 22002, headline: "Circular - Holiday List - 2022", href: "#" },
    { id: 22001, headline: "Circular - Amendment in SAIL Casual Leave Rules", href: "#" }
  ]
}

