// src/lib/links.js
export const links = [
  // Quick Links
  {
    name: "ESS (Employee Self Service)",
    href: "#",
    icon: "BookUser",
    category: "quicklink",
  },
  {
    name: "IMS (Incident Management System)",
    href: "#",
    icon: "Siren",
    category: "quicklink",
  },
  {
    name: "BAMS (Attendance)",
    href: "#",
    icon: "Fingerprint",
    category: "quicklink",
  },
  {
    name: "SAIL Mail (mail.sail.in)",
    href: "#",
    icon: "Mail",
    category: "quicklink",
  },
  { name: "Employee Corner", href: "#", icon: "Users", category: "quicklink" },
  { name: "Find People", href: "#", icon: "Search", category: "quicklink" },

  // Department Sites (Alphabetically Sorted with Final Icons)
  { name: "B.E. Deptt", href: "#", icon: "Building2", category: "department" },
  {
    name: "Blast Furnace",
    href: "#",
    icon: "/blast-furnace.webp",
    category: "department",
  },
  { name: "C & IT", href: "#", icon: "Laptop", category: "department" },
  { name: "CCM", href: "#", icon: "Building2", category: "department" },
  { name: "CEM", href: "#", icon: "/cem.png", category: "department" },
  { name: "CHRD", href: "#", icon: "UserCog", category: "department" },
  { name: "CO & CC", href: "#", icon: "Factory", category: "department" },
  { name: "CSR", href: "#", icon: "Building2", category: "department" },
  {
    name: "Design Deptt",
    href: "#",
    icon: "DraftingCompass",
    category: "department",
  },
  { name: "ECD", href: "#", icon: "Building2", category: "department" },
  { name: "EMD", href: "#", icon: "Building2", category: "department" },
  { name: "Elec. Repair Shop", href: "#", icon: "Cog", category: "department" },
  { name: "ETL", href: "#", icon: "CircuitBoard", category: "department" },
  { name: "Finance", href: "#", icon: "Landmark", category: "department" },
  { name: "Fire Service", href: "#", icon: "Flame", category: "department" },
  { name: "HR", href: "#", icon: "Users", category: "department" },
  { name: "HR-OD", href: "#", icon: "Building2", category: "department" },
  { name: "IAD", href: "#", icon: "Building2", category: "department" },
  { name: "IED", href: "#", icon: "Building2", category: "department" },
  { name: "Instrumentation", href: "#", icon: "Gauge", category: "department" },
  { name: "M & HS", href: "#", icon: "HeartPulse", category: "department" },
  {
    name: "Merchant Mill",
    href: "#",
    icon: "/tmt-bar.webp",
    category: "department",
  },
  { name: "MM & MKTG", href: "#", icon: "Building2", category: "department" },
  { name: "MSM", href: "#", icon: "Building2", category: "department" },
  {
    name: "Plant Garage",
    href: "#",
    icon: "/dumper-icon.png",
    category: "department",
  },
  { name: "PMD", href: "#", icon: "Building2", category: "department" },
  { name: "PPCD", href: "#", icon: "Building2", category: "department" },
  { name: "Projects", href: "#", icon: "GanttChartSquare", category: "department" },
  { name: "R & C Lab", href: "#", icon: "Microscope", category: "department" },
  {
    name: "RMHP",
    href: "#",
    icon: "/conveyorbelt.webp",
    category: "department",
  },
  { name: "राजभाषा", href: "#", icon: "/hindi.svg", category: "department" },
  { name: "Roll Design", href: "#", icon: "Cylinder", category: "department" },
  { name: "Safety", href: "#", icon: "Shield", category: "department" },
  {
    name: "Section Mill",
    href: "#",
    icon: "/joist-icon.jpg",
    category: "department",
  },
  { name: "SIGS", href: "#", icon: "Building2", category: "department" },
  { name: "Sinter Plant", href: "#", icon: "Factory", category: "department" },
  { name: "SMS", href: "#", icon: "Factory", category: "department" },
  { name: "Telecom", href: "#", icon: "Signal", category: "department" },
  {
    name: "Town Services",
    href: "#",
    icon: "Building",
    category: "department",
  },
  { name: "Traffic", href: "#", icon: "/train.png", category: "department" },
  { name: "Vigilance", href: "#", icon: "Eye", category: "department" },
  {
    name: "Wheel & Axle",
    href: "#",
    icon: "/wheel-axle-icon.jpg",
    category: "department",
  },
  { name: "Water Mgmt", href: "#", icon: "Waves", category: "department" },
  {
    name: "Wagon Repair",
    href: "#",
    icon: "/wagon-icon.jpg",
    category: "department",
  },
];
