// src/lib/links.js
export const links = [
  // Quick Links (Alphabetically Sorted)
  {
    title: "BAMS",
    subtitle: "(Attendance)",
    href: "#",
    icon: "Fingerprint",
    category: "quicklink",
  },
  {
    title: "Circular",
    subtitle: "(Personnel)",
    href: "#",
    icon: "FileText",
    category: "quicklink",
  },
  {
    title: "DCIS",
    href: "#",
    icon: "Database",
    category: "quicklink",
  },
  {
    title: "DSP Online",
    href: "#",
    icon: "MonitorSmartphone",
    category: "quicklink",
  },
  {
    title: "e-Slr/e-Std/File",
    href: "#",
    icon: "FileText",
    category: "quicklink",
  },
  {
    title: "ECS",
    href: "#",
    icon: "Wallet",
    category: "quicklink",
  },
  {
    title: "Employee Corner",
    href: "#",
    icon: "Users",
    category: "quicklink",
  },
  {
    title: "ERP Portal",
    href: "#",
    icon: "Network",
    category: "quicklink",
  },
  {
    title: "ESS",
    href: "#",
    icon: "UserCheck",
    category: "quicklink",
  },
  {
    title: "Find People",
    href: "#",
    icon: "Search",
    category: "quicklink",
  },
  {
    title: "HRIS-EX",
    href: "#",
    icon: "UserCog",
    category: "quicklink",
  },
  {
    title: "ICS",
    href: "#",
    icon: "Warehouse",
    category: "quicklink",
  },
  {
    title: "IMS",
    href: "https://ims-revamp.vercel.app/login",
    icon: "Database",
    category: "quicklink",
  },
  {
    title: "IRM",
    href: "#",
    icon: "ShieldCheck",
    category: "quicklink",
  },
  {
    title: "IspatCreditSoc.In",
    href: "#",
    icon: "Banknote",
    category: "quicklink",
  },
  {
    title: "LIS",
    href: "#",
    icon: "Library",
    category: "quicklink",
  },
  {
    title: "Mob. Search",
    href: "#",
    icon: "Smartphone",
    category: "quicklink",
  },
  {
    title: "New PHS",
    href: "#",
    icon: "FilePlus2",
    category: "quicklink",
  },
  {
    title: "PDS Search",
    href: "#",
    icon: "PackageSearch",
    category: "quicklink",
  },
  {
    title: "PHS",
    href: "#",
    icon: "File",
    category: "quicklink",
  },
  {
    title: "QCIS",
    href: "#",
    icon: "ClipboardCheck",
    category: "quicklink",
  },
  {
    title: "RACE",
    href: "#",
    icon: "Siren",
    category: "quicklink",
  },
  {
    title: "SAIL Mail",
    subtitle: "(mail.sail.in)",
    href: "https://email.sail.in/",
    icon: "Mail",
    category: "quicklink",
  },   
  {
    title: "SI STOCK",
    href: "#",
    icon: "Boxes",
    category: "quicklink",
  },
  {
    title: "Vistex",
    href: "#",
    icon: "BarChart3",
    category: "quicklink",
  },
  {
    title: "VRS Online",
    href: "#",
    icon: "UserCheck",
    category: "quicklink",
  },
  {
    title: "Webmail",
    href: "#",
    icon: "Mails",
    category: "quicklink"
  },

  // Department Sites (Alphabetically Sorted with Final Icons)
  { title: "B.E. Deptt", href: "#", icon: "Award", category: "department" },
  {
    title: "Blast Furnace",
    href: "#",
    icon: "/blast-furnace.png",
    category: "department",
  },
  { title: "C & IT", href: "#", icon: "Laptop", category: "department" },
  { title: "CCM", href: "#", icon: "Construction", category: "department" },
  { title: "CEM", href: "#", icon: "/cem.png", category: "department" },
  { title: "CHRD", href: "#", icon: "UserCog", category: "department" },
  {
    title: "CO & CC",
    href: "#",
    icon: "/coke-oven-batteries-preview.png",
    category: "department",
  },
  { title: "CSR", href: "#", icon: "HeartHandshake", category: "department" },
  {
    title: "Design Deptt",
    href: "#",
    icon: "DraftingCompass",
    category: "department",
  },
  { title: "ECD", href: "#", icon: "Leaf", category: "department" },
  { title: "EMD", href: "#", icon: "Zap", category: "department" },
  { title: "Elec. Repair Shop", href: "#", icon: "Cog", category: "department" },
  { title: "ETL", href: "#", icon: "CircuitBoard", category: "department" },
  { title: "Finance", href: "#", icon: "Landmark", category: "department" },
  { title: "Fire Service", href: "#", icon: "Flame", category: "department" },
  { title: "HR", href: "#", icon: "Users", category: "department" },
  { title: "HR-OD", href: "#", icon: "Users", category: "department" },
  { title: "IAD", href: "#", icon: "Receipt", category: "department" },
  { title: "IED", href: "#", icon: "Ruler", category: "department" },
  { title: "Instrumentation", href: "#", icon: "Gauge", category: "department" },
  { title: "M & HS", href: "#", icon: "HeartPulse", category: "department" },
  {
    title: "Merchant Mill",
    href: "#",
    icon: "/tmt-bar.png",
    category: "department",
  },
  { title: "MM & MKTG", href: "#", icon: "Package", category: "department" },
  { title: "MSM", href: "#", icon: "Factory", category: "department" },
  {
    title: "Plant Garage",
    href: "#",
    icon: "/dumper-icon.png",
    category: "department",
  },
  { title: "PMD", href: "#", icon: "Lightbulb", category: "department" },
  { title: "PPCD", href: "#", icon: "ClipboardList", category: "department" },
  {
    title: "Projects",
    href: "#",
    icon: "GanttChartSquare",
    category: "department",
  },
  { title: "R & C Lab", href: "#", icon: "Microscope", category: "department" },
  {
    title: "RMHP",
    href: "#",
    icon: "/conveyorbelt.png",
    category: "department",
  },
  { title: "राजभाषा", href: "#", icon: "/hindi.svg", category: "department" },
  { title: "Roll Design", href: "#", icon: "Cylinder", category: "department" },
  { title: "Safety", href: "#", icon: "Shield", category: "department" },
  {
    title: "Section Mill",
    href: "#",
    icon: "/joist-icon.png",
    category: "department",
  },
  { title: "SIGS", href: "#", icon: "Map", category: "department" },
  { title: "Sinter Plant", href: "#", icon: "Factory", category: "department" },
  { title: "SMS", href: "#", icon: "Factory", category: "department" },
  { title: "Telecom", href: "#", icon: "Signal", category: "department" },
  {
    title: "Town Services",
    href: "#",
    icon: "Building",
    category: "department",
  },
  { title: "Traffic", href: "#", icon: "/train.png", category: "department" },
  { title: "Vigilance", href: "#", icon: "Eye", category: "department" },
  {
    title: "Wheel & Axle",
    href: "#",
    icon: "/wheel-axle-icon-modified.png",
    category: "department",
  },
  { title: "Water Mgmt", href: "#", icon: "Waves", category: "department" },
  {
    title: "Wagon Repair",
    href: "#",
    icon: "/wagon-icon.png",
    category: "department",
  },
];
